global:
  scrape_interval: 1s
  # scrape_timeout: 4s
  external_labels:
    monitor: "Monitoring"
scrape_configs:
  - job_name: "health-check"
    static_configs:
      - targets: ["health-check:8080"]

